name = "sing12"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "sg12.tingkehh.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sg12.tingkehh.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg12.tingkehh.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg12.tingkehh.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.sg12.tingkehh.us.kg"
custom_domain = true
[[routes]]
pattern = "ruangguru.com.sg12.tingkehh.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg12.tingkehh.us.kg"
custom_domain = true



[vars]
PROXYIP = "15.235.162.49:443"
UUID = "a2268dff-6dfa-4fb8-8a4c-91011b9034b9"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
